name: ServerBackup
main: lakwsh\ServerBackup
version: 4
load: POSTWORLD
author: lakwsh
website: https://lakwsh.net
api:
 - 1.0.0
 - 2.0.0
 - 3.0.0

commands:
 backup:
  usage: "请参考README.md文件"
  permission: ServerBackup.backup
  description: "备份服务器"
permissions:
 ServerBackup:
  default: false
   ServerBackup.backup:
    default: op